### ISSUE TITLE
Question about c_str use

### ISSUE THREAD

**Issue by tejom** [bwasty/learn-opengl-rs#15]
Hey, Sorry not an issue, just a question and Im not sure how else to ask.

Ive been trying to do the same thing you did here in this repo for that opengl tutorial. I was stuck with no real errors.

I was doing this ` gl::GetUniformLocation(shader.id, "model".as_ptr() as *const i8);` and it was working until 1_6_1.

If you look at some of your code like 1_6_1 you use a macro to create a CStr.

If i did something like 
```
gl::GetUniformLocation(shader.id, "model".as_ptr() as *const i8);
gl::GetUniformLocation(shader.id, "view".as_ptr() as *const i8);
```

My square wouldn't render. I copied your macro for cstr and it worked.

How did you figure out that you needed to use a CStr in that function the way you did?

**Comment by alteous** [comment]
OpenGL is a C library. Rust strings are not C style strings but rather UTF-8 encoded strings which lack the terminating null byte marking the end of the string.

The below would have worked too without the use of `cstr!`:
```rust
gl::GetUniformLocation(id, b"model\0".as_ptr() as *const i8);
```

**Comment by bwasty** [comment]
Yes, exactly. And I found it it better to do in in a macro instead of a helper function, because I didn't want any string operations (concatenating `\0`) to happen at runtime during the render loop.
