### ISSUE TITLE
Cant run any example after 1_4_1

### ISSUE THREAD

**Issue by Japaxa2011gr** [bwasty/learn-opengl-rs#34]
```
thread '<unnamed>' panicked at 'attempted to leave type `nodrop::NoDrop<(epoch::Epoch, garbage::Bag)>` uninitialized, which is invalid', /home/nick/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:671:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Segmentation fault
```
os : linux debian 10
version: rustc 1.51.0

**Comment by jestarray** [comment]
how'd you fix it?  i ran into this same error on 1_5_1. also on 1.51.0 on arch linux. The problem seems to be tied to loading an image... so the image crate needs updating

**Comment by Japaxa2011gr** [comment]
I compiled the lesson source code  as a different project and somehow it worked

**Comment by 4nte** [comment]
I'm having the same issue, on 1_4_1. Running Manjaro/arch linux.
